parameters:
    akuma_core.abstract.form.class: Akuma\Bundle\CoreBundle\Form\AbstractFormType

services:
    akuma_core.abstract.form:
        public: true
        abstract: true
        class: %akuma_core.abstract.form.class%
        calls:
            - [setContainer, ["@service_container"]]